version: '3.0'

services:
    registry:
      container_name: registry
      image: registry
      volumes: 
        - "/opt/images:/var/lib/registry"
      ports:
        - "5000:5000"
      restart: always